// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-UqDxJADf56zCsgXtY7ioaZYUtCrkgQg',
    appId: '1:119947379250:web:23c47903302b25eaa7722b',
    messagingSenderId: '119947379250',
    projectId: 'pet-shop-app-ee6f2',
    authDomain: 'pet-shop-app-ee6f2.firebaseapp.com',
    storageBucket: 'pet-shop-app-ee6f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbmlg1unkeV09_qMSXXtBIBy8r_tuftq0',
    appId: '1:119947379250:android:27bc0755d2439af2a7722b',
    messagingSenderId: '119947379250',
    projectId: 'pet-shop-app-ee6f2',
    storageBucket: 'pet-shop-app-ee6f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOgQrrTafHHsbb_17nc3dBkQZH_fR3dT0',
    appId: '1:119947379250:ios:c3a6a153f9f0e15da7722b',
    messagingSenderId: '119947379250',
    projectId: 'pet-shop-app-ee6f2',
    storageBucket: 'pet-shop-app-ee6f2.firebasestorage.app',
    iosBundleId: 'com.petsworld.shop',
  );
}
